### ISSUE TITLE
Compiling issue - rtlsdr_set_bias_tee

### ISSUE THREAD

**Issue by sm3ulc** [dernasherbrezon/sdr-server#3]
On a updated debian/buster i get:

[ 67%] Linking C executable sdr_server
/usr/bin/ld: libsdr_serverLib.a(core.c.o): in function `start_rtlsdr':
core.c:(.text+0x54c): undefined reference to `rtlsdr_set_bias_tee'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sdr_server.dir/build.make:89: sdr_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:258: CMakeFiles/sdr_server.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Old rtl-lib? minimum version to run?

apt-cache show librtlsdr-dev | grep Version
Version: 0.6-1

**Comment by dernasherbrezon** [comment]
It looks like apt has stock librtlsdr. Without the latest bias-tee fixes. I will fix that.

In the meantime, can you build rtl-sdr by steve-m:
https://github.com/steve-m/librtlsdr/commits/master

**Comment by jeffreypkelly** [comment]
I also received the error on a RPI 3B

libsdr_serverLib.a(core.c.o): In function `start_rtlsdr':
core.c:(.text+0x8b0): undefined reference to `rtlsdr_set_bias_tee'
collect2: error: ld returned 1 exit status
CMakeFiles/sdr_server.dir/build.make:99: recipe for target 'sdr_server' failed
make[2]: *** [sdr_server] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/sdr_server.dir/all' failed
make[1]: *** [CMakeFiles/sdr_server.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

TY!

**Comment by sm3ulc** [comment]
Using the https://github.com/rtlsdrblog/rtl-sdr-blog repo seem to work fine. Important since it contains support for direct sampling.

**Comment by dernasherbrezon** [comment]
Fixed. The minimum librtlsdr version is 0.5.4.
