### ISSUE TITLE
sdr-server clients

### ISSUE THREAD

**Issue by atlex** [dernasherbrezon/sdr-server#5]
Hello,

Could you please provide some information about sdr-server's clients? How to connect to the sdr-server?
I tried CubicSDR and GQRX on macOS but there is no connection to the sdr-server.

Thanks,
Alex

**Comment by dernasherbrezon** [comment]
Hi Alex,

I think the only supported clients are C-clients (written in C language). Someone has to write support for sdr-server in UI applications.
