### ISSUE TITLE
[Question] RTL-SDR samples format

### ISSUE THREAD

**Issue by RandDruid** [dernasherbrezon/sdr-server#9]
Hello,

I am implementing HackRF support for the fork of 'sdr-server' project. One of the differences between boards is the sample format. As far as I know RTL-SDR outputs unsigned bytes, while HackRF outputs signed bytes.
When I take a look at 'process' function in 'xlating.c', I can see that you are already treating input as signed bytes:

```c
void process(const uint8_t *input, size_t input_len, float complex **output, size_t *output_len, xlating *filter) {
  // input_len cannot be more than (working_len_total - history_offset)

  // convert to [-1.0;1.0] working buffer
  volk_8i_s32f_convert_32f_u(filter->working_buffer + filter->history_offset, (const signed char *) input, 128.0F, input_len);

 // ....
}
```
it works with HackRF (I tested it). But would it actually work correctly with RTL-SDR for values in 128-255 range?

**Comment by dernasherbrezon** [comment]
It actually won't. I just tested and it indeed incorrectly represent this range. I'm going to test and release fix soon.
